name = "cantabile"
main = "worker.js"
compatibility_date = "2026-06-08"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[vars]
DATABASE_RUNTIME = "d1"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "cantabile"

[[d1_databases]]
binding = "DB"
database_name = "cantabile"
database_id = "46cbd083-985a-4c22-a6d2-5ad302f89957"
migrations_dir = "drizzle/d1"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "cantabile-images"

[observability]
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
